### ISSUE TITLE
Conflict between webview and pusher beam in app Flutter

### ISSUE THREAD

**Issue by chuvanhoang888** [pusher/push-notifications-flutter#37]
**When I use JavascriptChannel send webviewController.runJavascript(dataJs) of webview the app immediately cannot receive notifications from pusher beam but the app can still receive notifications in background**

Please see the image below

![image](https://user-images.githubusercontent.com/104492264/207277893-e077901c-d333-4497-9dc6-5f8521dbcf06.png)
![image](https://user-images.githubusercontent.com/104492264/207278006-6a751037-433e-4744-89d0-2c9f8b62b2ca.png)
![image](https://user-images.githubusercontent.com/104492264/207278780-799c384b-7e1b-4745-bce2-60ace979970b.png)

**Comment by chuvanhoang888** [comment]
**I get an error when I use webview to send a piece of dataJs to the server, there seems to be a channel conflict between Beams and Webview "webviewController.runJavascript(dataJs);"**

![image](https://user-images.githubusercontent.com/104492264/209047132-40aa2d5b-8e45-4003-8396-1ebff2ead8f3.png)
![image](https://user-images.githubusercontent.com/104492264/209047176-f63ef629-555c-41b1-85d5-a708e3e16ccc.png)

![image](https://user-images.githubusercontent.com/104492264/209047215-6292eca1-74ce-409b-8a43-d5a390dbd623.png)
![image](https://user-images.githubusercontent.com/104492264/209047229-49b7743d-3ded-4606-ad28-7d8d9199228c.png)
![image](https://user-images.githubusercontent.com/104492264/209047249-c98e8946-b8d2-4e14-abd0-0df846da8310.png)

**Comment by benjamin-tang-pusher** [comment]
I tested this in the Android emulator with Flutter Webview running in the foreground, and its able to successfully  receive Beams notifications:
`D/com.pusher.pusher_beams.PusherBeamsPlugin$onMessageReceivedInTheForeground$1$1@3b0e62e( 6069): Message received: {title=testing, body=test test test, data={pusher={"instanceId":"xxxxxxx","hasDisplayableContent":true,"publishId":"pubid-c79f50ce-8772-432c-bd20-4b05c43f4654"}}}`
Do you at least get the above log in your logcat? I also didn't test with JavascriptMode.unrestricted. If you do not use JavascriptMode.unrestricted, does it successfully receive foreground messages? 

My code looks like this:

```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final BeamsAuthProvider provider = BeamsAuthProvider()
    ..authUrl = "aaaaa"
    ...
  const instanceID = 'aaaaa';
  await PusherBeams.instance.start(instanceID);
  await PusherBeams.instance.setDeviceInterests(['debug-new', 'hello']);
  PusherBeams.instance.onMessageReceivedInTheForeground(
      (notification) => print("Run notification handling: $notification"));
  runApp(
    const MaterialApp(
      home: WebViewApp(),
    ),
  );
}
class WebViewApp extends StatefulWidget {
  const WebViewApp({super.key});
  @override
  State<WebViewApp> createState() => _WebViewAppState();
}
...
```

**Comment by benjamin-tang-pusher** [comment]
I will close this due to no response.

**Comment by chuvanhoang888** [comment]
Dear Sir,
I am sending this email to give you test code and error video on ios.
thankyou.

path_provider: ^2.0.11
pusher_beams: ^1.1.1
flutter_local_notifications: ^9.3.2
webview_flutter_android: ^3.0.0
webview_flutter_wkwebview: ^3.0.0
 Screen Recording 2023-03-20 at 17.12.32.mov
<https://drive.google.com/file/d/16nou0mfsPrB7f5UyATXGx5JdNmgBDsLi/view?usp=drive_web>

Vào Th 2, 27 thg 2, 2023 vào lúc 21:24 Benjamin Tang <
***@***.***> đã viết:
