### ISSUE TITLE
setUserId got error 401 in Android, but worked in iOS

### ISSUE THREAD

**Issue by YanaWijaya** [pusher/push-notifications-flutter#38]
I've got this error message when trying to setUserId() in Android
![image](https://user-images.githubusercontent.com/112671773/209144445-17a83b16-2ebd-4f9c-b652-7c1be3a0848e.png)

It's strange because it works fine in iOS.

Response from the BE server:
`{"token":"eyJhbG......."}`

This is how I use the setUserId:
![image](https://user-images.githubusercontent.com/112671773/209145207-0b9540ac-7a89-4a89-8ca9-793950173169.png)
![image](https://user-images.githubusercontent.com/112671773/209145234-87440d09-ddab-4cdb-946b-b2b121cdbdb1.png)

**Comment by benw-pusher** [comment]
The 401 response would indicate the server did not authorize the incoming auth request. You might need to add some logging on the server to identify why this is the case - perhaps the cookie is not being set correctly? 
You also shouldn't need to append the `userGuid` to the `authUrl`, the library should automatically pass the userId specified when `PusherBeams.instance.setUserId` is invoked. The user ID is the first parameter for this method. 
Let us know if this helps.

**Comment by benw-pusher** [comment]
We haven't had a response here so I will close, if you need further assistance please get in touch at https://support.pusher.com/hc/en-us/requests/new
