### ISSUE TITLE
Callback when clicking notification banner

### ISSUE THREAD

**Issue by YanaWijaya** [pusher/push-notifications-flutter#39]
Hello

Is there any event callback that I can use to catch user clicks event on notification banner when the app is minimized?
On the [docs](https://pusher.com/docs/beams/guides/handle-incoming-notifications/flutter/) I only see this event "onMessageReceivedInTheForeground" to catch user clicks, but it didn't work when app is minimized.

I've seen it on Pusher Channel there is a callback called "onEvent". But I didn't find something similar to that on beams.

**Comment by benjamin-tang-pusher** [comment]
Hi, unfortunately the flutter beams library does not have a method for handling pressing the notification when it is minimized, currently there is only a method for the foreground as you mentioned.

We're aware of this, but adding this method is not currently on our roadmap.
