### ISSUE TITLE
[Bug] Notification tap message not received when app's opened from terminated state

### ISSUE THREAD

**Issue by rutvik110** [pusher/push-notifications-flutter#40]
### **Description**
I'm not able to receive the notification message that opened the app from terminated state. I'm trying to use `getInitialMessage` , but its not returning the notification data but returns null.

```dart
  final Map<String, dynamic>? pusherMessage =
        await PusherBeams.instance.getInitialMessage();
```
This is currently tested on ios, I'll check on android once and add the android stats later.

**Comment by Nithsua** [comment]
Any update on this issue?

**Comment by kayumarie** [comment]
Any update indeed?

**Comment by chris-cmsoft** [comment]
@rutvik110 Did you ever find a solution to this ?

**Comment by benw-pusher** [comment]
I believe this is a bug in the library and have escalated this to the engineering team for review and resolution. We'll update this issue when complete.

**Comment by rutvik110** [comment]
> @rutvik110 Did you ever find a solution to this ? 

Not really. We decided to not tackle it from our side as we were occupied with other things and this wasn't that much of a critical issue in our case.

**Comment by benw-pusher** [comment]
In order to receive data the published payload must contain an [info] key in the [data] key:


```
{
  "interests":["hello"],
  "apns": {
    "aps": {
      "alert": {"title":"Hello", "body":"Hello, world!"},
    },
   "data": {
      "info": { "name": "george" }
    }
  },
  "fcm": {
    "notification": {"title":"Hello", "body":"Hello, world!"},
    "data": {
      "info": { "name": "george" }
    }
  }
}
```
