### ISSUE TITLE
Please update uuid package dependency

### ISSUE THREAD

**Issue by Arthurius** [pusher/push-notifications-flutter#47]
We are using pusher_beans and Datadog in our project. Datadog recently updated and is relying on `uuid: ^4.0.0` which is incompatible with pusher_beams, because that relies on `uuid ^3.0.5`
Is it possible to update this?

Changelog for 4.0.0 is here, cheers. https://pub.dev/packages/uuid/changelog

Thanks

**Comment by shanaka-sync** [comment]
Use dependency overrides.

dependency_overrides:
  uuid: ^4.0.0
